### ISSUE TITLE
Other formats & Use of this spec?

### ISSUE THREAD

**Issue by LewisCowlesMotive** [plaid/plaid-postman#140]
I Work for a business that is working-towards OpenAPI3, and because we still have a bit of legacy, this makes working with OpenAPI 3 very difficult. Even using tools such as:

- https://apimatic.io
- [LucyBot tool I used to convert](https://github.com/LucyBot-Inc/api-spec-converter)
- [StackOverflow regarding OpenAPI2 and nullable](https://stackoverflow.com/questions/48111459/how-to-define-a-property-that-can-be-string-or-null-in-openapi-swagger)
- Plaid API docs base, which  I used to provide fully-qualified externalDocs url properties from

We are still seeing issues interacting with the provided schema. I wanted to create this issue to request if possible OpenAPI2 / Swagger, but also to see if there is anything else Plaid can do, or if others are also experiencing problems with this.

**Comment by phoenixy1** [comment]
So the OpenAPI v3 version of the Plaid spec is available here: https://github.com/plaid/plaid-openapi. We don't have an OpenAPI v2 version of the spec and are not currently planning to create one. It's possible there might be another way to solve the problem you're trying to address with usage of the OpenAPI spec -- I'm not sure what your business's use case for it is?

**Comment by LewisCowlesMotive** [comment]
Sorry I've posted to the incorrect repo 👍

**Comment by Zazzberry** [comment]
Who is this and where is my money

Sent from my Alcatel JOY TAB 2

On Jan 12, 2023 10:48 AM, Alex ***@***.***> wrote:
[External Email]

So the OpenAPI v3 version of the Plaid spec is available here: https://github.com/plaid/plaid-openapi<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fplaid%2Fplaid-openapi&data=05%7C01%7Ckrystal.williams%40student.csn.edu%7C77a761ef2f0f484cfe0508daf4cd9b92%7Cdf35d5749fba48cea073737868d77a48%7C0%7C0%7C638091461185537413%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=%2Fz4fLjcX6VjGtlBEH3393VGKIX8PZ%2BsPdtJjM2wD5ro%3D&reserved=0>. We don't have an OpenAPI v2 version of the spec and are not currently planning to create one. It's possible there might be another way to solve the problem you're trying to address with usage of the OpenAPI spec -- I'm not sure what your business's use case for it is?
