### ISSUE TITLE
stuck at Couldn't connect to your institution - Bank of America

### ISSUE THREAD

**Issue by jshrek** [plaid/plaid-postman#153]
So I got as far as entering the development client_id and secret_key and the env_url of development.plaid.com

Then I can click on CREATE LINK TOKEN and Send, and it comes back successful and I see the link_token is now set.

I then made a copy of link.html file and entered the same link_token as above.

When I run link.html in my browser, I click on LINK ACCOUNT and see Plaid popup saying its going use Plaid to connect to my account and I click CONTINUE.

It then asks me to select my Institution, so I click on Bank of America, and then I get back "Couldn't connect to your institution".

I am stuck and do not know what I should be looking for or looking at to debug the problem.

![boa](https://github.com/plaid/plaid-postman/assets/19673842/96795985-2bb4-42b2-bce5-71fce8241319)

**Comment by phoenixy1** [comment]
This is most likely because Bank of America requires OAuth registration and you haven't completed that process yet. To view your OAuth registration status and required next steps, see https://dashboard.plaid.com/settings/compliance/us-oauth-institutions
