### ISSUE TITLE
Linking account in dev results in internal error

### ISSUE THREAD

**Issue by mdk25** [plaid/plaid-postman#154]
After successfully sending API calls in the sandbox environment, I'm following the instructions to do so in the development environment, but getting an internal error after entering my username and password:

![internal_error](https://github.com/plaid/plaid-postman/assets/2078479/96dd883f-0949-416c-b98b-41f91c52d735)

**Comment by ioRekz** [comment]
Yes same error here. 
Screenshot of the console
<img width="546" alt="Screenshot 2024-02-12 at 12 00 55" src="https://github.com/plaid/plaid-postman/assets/688774/c93e1160-884c-4f7a-8b61-5d8a001189b0">

**Comment by mdk25** [comment]
Yeah, I found the rate limit error in the dashboard logs yesterday as well as the development environment access form, which I also submitted.

Assuming that's the only issue, it would probably be helpful to list this requirement in the readme here.

**Comment by mdk25** [comment]
Well, I'm now approved for development access, but can no longer even begin the linking process due to Plaid's content security policy:

![cdn](https://github.com/plaid/plaid-postman/assets/2078479/275d8f5e-73a6-405c-aa03-0b480b45d8f4)

@ioRekz I see this in your screenshot as well, how did you get past it?

**Comment by phoenixy1** [comment]
To follow up, we were able to identify this issue as being caused by a recent change to CSP validation. We are going to roll back these changes until we are confident we can restore them without disruption to customers.
