### ISSUE TITLE
Can you provide a version of the Postman Collection I can download without referencing postman.com 

### ISSUE THREAD

**Issue by gdombchik** [plaid/plaid-postman#175]
The ReadMe specifies _If you're not interested in reading these instructions, you can go directly to [the Plaid Postman collection](https://www.postman.com/plaid-api/workspace/plaid/collection/12160321-04d27ed8-aed4-4d46-a1f8-70a72ec9a78a)._
My company blocks postman.com.  I would like to import the postman collection into insomia.

**Comment by phoenixy1** [comment]
Sure, I've attached it below:

[Plaid API Endpoints_oct.postman_collection.json](https://github.com/user-attachments/files/17399776/Plaid.API.Endpoints_oct.postman_collection.json)

**Comment by gdombchik** [comment]
Thank You.
