### ISSUE TITLE
link.html file showing an internal error when launching link account client for prod

### ISSUE THREAD

**Issue by lestela57** [plaid/plaid-postman#176]
I've taken my link token from postman and entered it into my local link.html file and getting this error
![Screen Shot 2024-11-08 at 6 34 46 PM](https://github.com/user-attachments/assets/f204b72e-a7c1-4503-91c9-8ed99c1de4b1)
I've tried it in microsoft edge and safari, and have gotten this error message in the console: Blocked a frame with origin "null" from accessing a frame with origin "https://cdn.plaid.com".  The frame requesting access has a protocol of "file", the frame being accessed has a protocol of "https". Protocols must match.
You can see it here:
![Screen Shot 2024-11-08 at 6 39 06 PM](https://github.com/user-attachments/assets/1fed3306-4ee6-4e40-99b0-29989f329514)

**Comment by phoenixy1** [comment]
Can you try in Chrome? It's been verified to work in Chrome. (Although it works for me in Safari as well.)

Alternatively, if it's not working for you, you can achieve the same result using Plaid's new Hosted Link feature:

1. Call `/link/token/create` with `hosted_link: {}` in the request body, and your response will contain a URL with a link session, in addition to the `link_token`. 
2. You can go to that URL and complete the Link flow
3. Use Postman to call `/link/token/get` on the `link_token` you got in step 1
4. The response will contain a `public_token`, and then you can proceed as normal, using Postman to exchange the public token for an access token.

**Comment by lestela57** [comment]
Thanks for the quick response! I'm getting the same "internal error ocurred" on chrome, both when loading it via link.html and when loading it via the hosted link: 
![Screen Shot 2024-11-08 at 7 45 12 PM](https://github.com/user-attachments/assets/46dc0e21-8169-44b0-add5-65070a388d8a)

**Comment by lestela57** [comment]
I've tried on different computers, with the same issue. This is what I'm getting on the safari console: 
![Screen Shot 2024-11-09 at 5 27 55 PM](https://github.com/user-attachments/assets/48571e4c-c3c0-4013-8285-7be242abd4a2)

**Comment by phoenixy1** [comment]
Are you able to launch Link via the QuickStart app? This seems like it may be an issue with your account or how you are calling /link/token/create. The client side errors may be being caused by the server error. 

Can you provide some link_session_ids you are having g this issue with for troubleshooting?

**Comment by lestela57** [comment]
Hey Alex! thanks again for answering on a Sunday. I'll go through the quickstart and see if I can launch the link. 
These are the events I'm getting:
"link_sessions": [
        {
            "events": [
                {
                    "event_id": "28564989-5445-43bd-bcb8-de61197a1121",
                    "event_metadata": {
                        "request_id": "V4YmkclE8FWRSlM",
                        "view_name": "ERROR"
                    },
                    "event_name": "OPEN",
                    "timestamp": "2024-11-10T19:34:08Z"
                },
                {
                    "event_id": "4ef025eb-5124-4065-929a-b9dd553af8d6",
                    "event_metadata": {
                        "error_code": "INTERNAL_SERVER_ERROR",
                        "error_message": "an unexpected error occurred",
                        "error_type": "API_ERROR",
                        "request_id": "V4YmkclE8FWRSlM"
                    },
                    "event_name": "ERROR",
                    "timestamp": "2024-11-10T19:34:07Z"
                },
                {
                    "event_id": "0697abdd-8dc0-4eb5-ba5a-447b9023937b",
                    "event_metadata": {
                        "request_id": "V4YmkclE8FWRSlM",
                        "view_name": "ERROR"
                    },
                    "event_name": "TRANSITION_VIEW",
                    "timestamp": "2024-11-10T19:34:07Z"
                }
            ],
            "link_session_id": "4a64b398-689a-4f24-89fd-78ca2c130c6f",
            "results": {
                "bank_income_results": [],
                "cra_item_add_results": [],
                "document_income_results": null,
                "item_add_results": [],
                "payroll_income_results": []
            },
            "started_at": "2024-11-10T19:34:07.687523108Z"
        }
    ],

**Comment by phoenixy1** [comment]
@lestela57 the issue is that you need to set up a use case, which you can do here: https://dashboard.plaid.com/link/data-transparency-v5

**Comment by lestela57** [comment]
Oh I see. I activated the development phase a few years ago, which is now partially production? I thought I had access to 200 transaction connections with the set up I have currently

**Comment by lestela57** [comment]
It worked!! Thanks again for the quick responses and looking into this on the weekend
