### ISSUE TITLE
Postman collection is not working.

### ISSUE THREAD

**Issue by maurangzebwwcny** [plaid/plaid-postman#24]
When i tried to open postman collection as per the given URL. The following comes up. No Workspace exists.

Please do some needfull.

**Comment by phoenixy1** [comment]
Hi @maurangzebwwcny, sorry for the trouble! I'm not able to reproduce this problem.  Would you be able to provide a bit more detail (where did you find the URL and what URL is it, where does the error appear, a screenshot of the error if possible) to help us investigate?  Thanks!
