### ISSUE TITLE
Set env_url?

### ISSUE THREAD

**Issue by kwantx** [plaid/plaid-postman#32]
Hi, 

I am using plaid-postman for the first time and continuously receive an error when trying to send a request. What is the correct env_url to provide? Example: My postman sandbox environment is called 'Plaid' - but cannot send request for the following: 

'https://{{env_url}}/link/token/create'
'https://{{Plaid}}/link/token/create'

Error: getaddrinfo ENOTFOUND {{env_url}}

Thank you in advance.

**Comment by kwantx** [comment]
The problem begins in #3 of Getting Started: 'Run in Postman' does not create an environment variable, and no guidance is provided on how to import the Plaid-specific environment variables.

**Comment by Estete9** [comment]
I had the same problem. I found an old collection where it does have the environment. Create a new environment with the variables (without quotes): "client_id", "secret_key", "public_token", "access_token", "asset_report_token", "env_url", "account_id".
For the "env_url" set the value to "sandbox.plaid.com"

This should work :)

**Comment by phoenixy1** [comment]
this should now be resolved!
