### ISSUE TITLE
Postman Collection doesn't have an environment

### ISSUE THREAD

**Issue by Estete9** [plaid/plaid-postman#33]
Hello, I've been 2 days trying to figure this out, when you click on "run in Postman" it creates the collection but not the environment. I found an old collection that contains the environment "sandbox" but it requires a "public_key".
I solved this by copying the values from the old collection's sandbox environment into the new collection.
I think this is what the previous issues by @kwantx and @maurangzebwwcny are about.

**Comment by phoenixy1** [comment]
This should now be fixed!
