### ISSUE TITLE
Missing /sandbox/bank_transfer/fire_webhook

### ISSUE THREAD

**Issue by imtibbet** [plaid/plaid-postman#49]
https://plaid.com/docs/api/sandbox/#sandboxbank_transferfire_webhook

**Comment by mcammallere13** [comment]
https://github.com/plaid/plaid-postman/issues

**Comment by phoenixy1** [comment]
Thanks for reporting this! We are removing Bank Transfers endpoints from Postman altogether as we move toward steering new users to the Transfers endpoints rather than the Bank Transfers ones. So I am going to close this particular issue as wontfix.
