### ISSUE TITLE
Create Link Token - OAuth redirect URI must be configured in the developer dashboard

### ISSUE THREAD

**Issue by rmeske** [plaid/plaid-postman#51]
When testing with Postman and the sandbox, how do I reconfigure the redirect URI.  There is one included as part of the body, and when I remove that the error goes away.  

Should the redirect_url be removed for all cases now?

**Comment by Tarious1** [comment]
Run sandbox

**Comment by Tarious1** [comment]
> When testing with Postman and the sandbox, how do I reconfigure the redirect URI.  There is one included as part of the body, and when I remove that the error goes away.  
> 
> Should the redirect_url be removed for all cases now?

Is the issue fixed?

**Comment by rmeske** [comment]
I never received a response.

**Comment by phoenixy1** [comment]
Sorry for the delay in responding! For basic sandbox desktop web testing, a redirect_uri is not required.

**Comment by Tarious1** [comment]
Was you able to run the sandbox?
