### ISSUE TITLE
Postman environment variable not imported when clicking "Run in Postman"

### ISSUE THREAD

**Issue by chrisweis** [plaid/plaid-postman#65]
Hello,

Following your instructions here...
https://github.com/plaid/plaid-postman

...and its text "Once both the collection and the environment variables are imported into Postman" doesn't seem to match the Postman behavior.  When I click "Run in Postman" it successfully imports the collection, but not any environments.

Thanks,
Chris

**Comment by phoenixy1** [comment]
Thanks for reporting! I think I must have forgotten to check the box to export the environment variables the last time I exported the collection. I'll re-export it now and this should be fixed once https://github.com/plaid/plaid-postman/pull/64 is merged.
