### ISSUE TITLE
Documentation doesn't match Postman collection

### ISSUE THREAD

**Issue by chrisweis** [plaid/plaid-postman#66]
Hello,

In readme.md here...
https://github.com/plaid/plaid-postman

...theis text seems incorrect:
"Plaid API Endpoints -> Items -> Create Item [Sandbox Only]" 

...and it should be:
"Plaid API Endpoints -> Items -> Item Creation -> Create Item [Sandbox Only]"

Thanks,
Chris

**Comment by phoenixy1** [comment]
Thanks for reporting! I just added a fix to this to https://github.com/plaid/plaid-postman/pull/64
