### ISSUE TITLE
Step 12: 429 (Too Many Requests)

### ISSUE THREAD

**Issue by andresn** [plaid/plaid-postman#76]
Hi there, thank you for this great resource. Please note I'm seeing the following on Step 12 if you can please advise:

Console: POST https://development.plaid.com/link/item/mfa 429 (Too Many Requests)

Browser > link.html:
<img width="433" alt="image" src="https://user-images.githubusercontent.com/69597/160738235-a231b904-89d7-4346-a063-43f6d541b63d.png">

**Comment by andresn** [comment]
... I tried with multiple banks and same situation. Also, I tried getting a new/fresh link_token, but same difference.

**Comment by andresn** [comment]
... nevermind, it looks like it's likely due to not having applied for access to a dev account first.

**Comment by phoenixy1** [comment]
Glad you've got it figured out! This can also happen if you accidentally use the Sandbox test credentials instead of real credentials in Production or Development.
